# TCL File Generated by Component Editor 13.0sp1
# Tue Dec 06 11:39:22 EST 2016
# DO NOT MODIFY


# 
# neural_net_accelerator "neural_net_accelerator" v1.0
#  2016.12.06.11:39:22
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module neural_net_accelerator
# 
set_module_property DESCRIPTION ""
set_module_property NAME neural_net_accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME neural_net_accelerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL neunet_accel_mm_register_array
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file neunet_accel_mm_register_array.sv SYSTEM_VERILOG PATH source/hardware/neunet_accel_mm_register_array.sv TOP_LEVEL_FILE
add_fileset_file ieee754_mul.v VERILOG PATH source/hardware/ieee754_mul.v
add_fileset_file mac_if.vh OTHER PATH source/hardware/mac_if.vh
add_fileset_file neunet_mac.sv SYSTEM_VERILOG PATH source/hardware/neunet_mac.sv
add_fileset_file quadport_ram.sv SYSTEM_VERILOG PATH source/hardware/quadport_ram.sv
add_fileset_file quadport_ram_if.vh OTHER PATH source/hardware/quadport_ram_if.vh
add_fileset_file regfile.sv SYSTEM_VERILOG PATH source/hardware/regfile.sv
add_fileset_file sigmoid.sv SYSTEM_VERILOG PATH source/hardware/sigmoid.sv
add_fileset_file sigmoid_if.vh OTHER PATH source/hardware/sigmoid_if.vh
add_fileset_file arbiter.sv SYSTEM_VERILOG PATH source/hardware/arbiter.sv
add_fileset_file feedforward_controller.sv SYSTEM_VERILOG PATH source/hardware/feedforward_controller.sv
add_fileset_file ieee754_add.v VERILOG PATH source/hardware/ieee754_add.v
add_fileset_file ieee754_div.v VERILOG PATH source/hardware/ieee754_div.v
add_fileset_file ieee754_exp.v VERILOG PATH source/hardware/ieee754_exp.v
add_fileset_file dualport_ram_controller.sv SYSTEM_VERILOG PATH source/hardware/dualport_ram_controller.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL neunet_accel_mm_register_array
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file neunet_accel_mm_register_array.sv SYSTEM_VERILOG PATH source/hardware/neunet_accel_mm_register_array.sv {ALDEC_SPECIFIC CADENCE_SPECIFIC MENTOR_SPECIFIC SYNOPSYS_SPECIFIC}
add_fileset_file ieee754_mul.v VERILOG PATH source/hardware/ieee754_mul.v
add_fileset_file mac_if.vh OTHER PATH source/hardware/mac_if.vh
add_fileset_file neunet_mac.sv SYSTEM_VERILOG PATH source/hardware/neunet_mac.sv
add_fileset_file quadport_ram.sv SYSTEM_VERILOG PATH source/hardware/quadport_ram.sv
add_fileset_file quadport_ram_if.vh OTHER PATH source/hardware/quadport_ram_if.vh
add_fileset_file regfile.sv SYSTEM_VERILOG PATH source/hardware/regfile.sv
add_fileset_file sigmoid.sv SYSTEM_VERILOG PATH source/hardware/sigmoid.sv
add_fileset_file sigmoid_if.vh OTHER PATH source/hardware/sigmoid_if.vh
add_fileset_file arbiter.sv SYSTEM_VERILOG PATH source/hardware/arbiter.sv
add_fileset_file feedforward_controller.sv SYSTEM_VERILOG PATH source/hardware/feedforward_controller.sv
add_fileset_file ieee754_add.v VERILOG PATH source/hardware/ieee754_add.v
add_fileset_file ieee754_div.v VERILOG PATH source/hardware/ieee754_div.v
add_fileset_file ieee754_exp.v VERILOG PATH source/hardware/ieee754_exp.v
add_fileset_file dualport_ram_controller.sv SYSTEM_VERILOG PATH source/hardware/dualport_ram_controller.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

