onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/clk
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reset
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/address
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/writedata
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/write
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/read
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/chipselect
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/readdata
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/readdata_reg
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/register_bank
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/loop_index
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ff_done
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/regfile_syn_rst
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/load_act
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg_sel_acc
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg_word_sel
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/add_en
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac_en
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sig_en
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg_act
add wave -noupdate -group top_level /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg_acc
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/CLK
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/RST
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/start_flg
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/mac_pipe_clr
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/sigmoid_pipe_clr
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/addr_w1
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/addr_w2
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/addr_b1
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/addr_b2
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/addr_act
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/size_l0
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/size_l1
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/size_l2
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/done_flg
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/layer_prep_stb
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/issue_mac
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/issue_add
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/issue_sigmoid
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/load_act_flg
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/reg_sel
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/word_sel
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_state
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/next_state
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/issues_remaining
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/mac_pipe_clear
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/pending_issues
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/pending_issues_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_layer_size
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_layer_size_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/nlayers
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/nlayers_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_layer
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_layer_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/weight_base_addr
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/act_base_addr
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_addr_w
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_addr_a
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/bias_base_addr
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_addr_b
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_addr_b_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/bias_base_addr_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_addr_w_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/curr_addr_a_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/weight_base_addr_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/act_base_addr_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/acts_remaining
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/acts_remaining_next
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/layers_pending
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/ram_load
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/ram_store
add wave -noupdate -group controller /nios_system_tb/nios_system_inst/neural_net_accelerator_0/ffctrl/ram_addr
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/addr
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/wen
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/ren
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/four
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/din_a
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/din_b
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/din_c
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/din_d
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/dout_a
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/dout_b
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/dout_c
add wave -noupdate -group ffc_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif1/dout_d
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/addr
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/wen
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/ren
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/four
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/din_a
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/din_b
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/din_c
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/din_d
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/dout_a
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/dout_b
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/dout_c
add wave -noupdate -group slave_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrif2/dout_d
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/addr
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/wen
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/ren
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/four
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/din_a
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/din_b
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/din_c
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/din_d
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/dout_a
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/dout_b
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/dout_c
add wave -noupdate -group out_qrif /nios_system_tb/nios_system_inst/neural_net_accelerator_0/arb/qrifo/dout_d
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/rst_syn
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/wdata
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/word_en
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/act_wen
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/acc_wen
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/acc_sel_w
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/acc_sel_r
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/rdata_act
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/rdata_acc
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/act_data
add wave -noupdate -group regfile /nios_system_tb/nios_system_inst/neural_net_accelerator_0/reg4/acc_data
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/clk
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reset
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_5
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_6
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_7
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_8
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_9
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_10
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p0_11
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_5
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_6
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_7
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_8
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_9
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_10
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p1_11
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_5
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_6
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_7
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_8
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_9
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_10
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p2_11
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_5
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_6
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_7
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_8
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_9
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_10
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/datac_p3_11
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/mul_result_p0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/mul_result_p1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/mul_result_p2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/mul_result_p3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/add_sub0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/add_sub1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/add_sub2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/add_sub3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/add_sub4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen5
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen6
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen7
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen8
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen9
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen10
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/reg_wen11
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel5
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel6
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel7
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel8
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel9
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel10
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/word_sel11
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index0
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index1
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index2
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index3
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index4
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index5
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index6
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index7
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index8
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index9
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index10
add wave -noupdate -group mac /nios_system_tb/nios_system_inst/neural_net_accelerator_0/mac/index11
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/clk
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reset
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/exp_out_p0
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/exp_out_p1
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/exp_out_p2
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/exp_out_p3
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/sub_out_p0
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/sub_out_p1
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/sub_out_p2
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/sub_out_p3
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/div0_p0
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/div0_p1
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/div0_p2
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/div0_p3
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/nan_p0
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/nan_p1
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/nan_p2
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/nan_p3
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel0
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel1
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel2
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel3
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel4
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel5
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel6
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel7
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel8
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel9
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel10
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel11
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel12
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel13
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel14
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel15
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel16
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel17
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel18
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel19
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel20
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel21
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel22
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel23
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel24
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel25
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel26
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel27
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel28
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/word_sel29
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index0
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index1
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index2
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index3
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index4
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index5
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index6
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index7
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index8
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index9
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index10
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index11
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index12
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index13
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index14
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index15
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index16
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index17
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index18
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index19
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index20
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index21
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index22
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index23
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index24
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index25
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index26
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index27
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index28
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/index29
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen0
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen1
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen2
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen3
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen4
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen5
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen6
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen7
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen8
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen9
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen10
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen11
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen12
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen13
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen14
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen15
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen16
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen17
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen18
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen19
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen20
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen21
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen22
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen23
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen24
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen25
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen26
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen27
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen28
add wave -noupdate -group sigmoid /nios_system_tb/nios_system_inst/neural_net_accelerator_0/sigmoid/reg_wen29
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {294 ps}
